version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: reeltrack_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reeltrack
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: reeltrack_backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/reeltrack?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - JWT_SECRET=5B1FE247B1EEAA7F1F89F95146D19E538E5AE4F8C4776D1FBA2B1E168F55
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: reeltrack_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  db_data:
